default: &default
  adapter: postgresql
  encoding: utf8
  pool: 5
  username: mirzoz
  password:

development:
  <<: *default
  database: nomina_development

test:
  <<: *default
  database: nomina_test